FROM gpdb:latest

WORKDIR /home/gpadmin

#Installation PXF
COPY ./debs/pxf-gp6-6.3.0-2-ubuntu18.04-amd64.deb ./
RUN set -ex; \
	sudo apt-get update; \
	sudo apt-get install -y --no-install-recommends openjdk-8-jdk curl; \
	sudo apt-get install -y --no-install-recommends ./pxf-gp6-6.3.0-2-ubuntu18.04-amd64.deb; \
	sudo rm -rf /var/lib/apt/lists/*; \
        sudo rm ./pxf-gp6-6.3.0-2-ubuntu18.04-amd64.deb; \
	sudo chown -R gpadmin:gpadmin /usr/local/pxf-gp*

#PXF Configuration
RUN set -e;\
	export GPHOME=/usr/local/greenplum-db; \
	export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64;\
	export PXF_HOME=/usr/local/pxf-gp6;\
	export PXF_BASE=/usr/local/pxf-gp6/base;\
	export PXF_LOADER_PATH=$PXF_BASE/lib;\
	export PXF_PORT=5998;\
	export GPDB_PXF_ENABLED="true";\
	/usr/local/pxf-gp6/bin/pxf prepare;\
	/usr/local/pxf-gp6/bin/pxf register;\
  	echo "source /usr/local/greenplum-db/greenplum_path.sh" >> ./.bashrc; \
	echo 'export PXF_BASE=/usr/local/pxf-gp6/base' >> ./.bashrc; \
	echo 'export PXF_HOME=/usr/local/pxf-gp6' >> ./.bashrc;\
	echo 'export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64' >> ./.bashrc;\
	echo 'export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64' >> /usr/local/pxf-gp6/base/conf/pxf-env.sh;\
	echo "export PXF_LOADER_PATH=$PXF_BASE/lib" >> /usr/local/pxf-gp6/base/conf/pxf-env.sh;\
	echo "export PXF_LOADER_PATH=$PXF_BASE/lib" >> ./.bashrc;\
	echo 'export PXF_PORT=5998' >> ./.bashrc;\
	echo 'export GPDB_PXF_ENABLED="true"' >> ./.bashrc;

